package com.codecombat.websocket;

public enum WsEventType {
    MATCH_FOUND,
    COUNTDOWN,
    MATCH_START,
    TIMER_UPDATE,
    PLAYER_CODING,
    PLAYER_RUNNING,
    PLAYER_SUBMITTED,
    PLAYER_ACCEPTED,
    PLAYER_WRONG,
    PLAYER_TLE,
    PLAYER_MLE,
    PLAYER_DISCONNECTED,
    PLAYER_RECONNECTED,
    MATCH_FINISHED,
    RATING_UPDATED,
    NOTIFICATION
}
